apiVersion: "v1"
kind: Component
class: App
includes:
  - microservices
metadata: 
  name: "client-metrics"
  description: "Ingests Metrics from Mobile and other connected devices"
  license: "private"
  logo: "edge.png"
  contact: "watchers@my-org.io"
  tier: "1"
dependencies:
  upstream: []
  downstream: ["edge-logs"]
  triggers: []
classification:
    tag: ["edge", "metrics"]
    domain: "platform"
    team: "watchers"
    capability: "observability"
properties:
  dev: 
    quickstart: "./gradlew runApp"
    local-run: "docker-compose up -d"
  operations:
    idempotent: "true"
contact:
  owner:
    id: "@user10"
  contributors:
    - id: "@user2"
  support:
    - id: "#metrics"
  participants:
    - id: "[observability]"

links:
  - type: "source"
    url: "https://github.com/edge-team/client-metrics"
  - type: "build"
    url: "https://jenkins/edge-team/client-metrics/build"
  - type: "docs"
    url: "https://scrolls/edge-team/client-metrics/intro"
  - type: "artifact"
    url: "https://quay.io/edge-team/client-metrics"

