apiVersion: "v1"
kind: Discovery
metadata: 
  name: "pg-discovery"

type: postgres
instance:
  - name: "pg-1"
    enabled: "${env.SSL_STATE==on}"
    includes:
      - internal
    classification:
      team: "datahoarders"
      domain: "storage"
      capability: "dataretention"
    options: 
      host: "postgres"
      port: "5432"
      username: "file:./tmp/pgusername"
      password: "file:./tmp/pgpassword"
      ssl: "true"
      cafile: "./tmp/ca.crt"
      database: "servicing"
      #ignore, skip, replace, mergeLeft, mergeRight
    duplicatesStrategy: "ignore" 

  - name: "pg-2"
    options: 
      host: "postgres"
      port: "5432"
      username: "file:./tmp/pgusername"
      password: "file:./tmp/pgpassword"
      ssl: "true"
      cafile: "./tmp/ca.crt"
      database: "preferences"
      #ignore, skip, replace, mergeLeft, mergeRight
    duplicatesStrategy: "ignore" 
