apiVersion: "v1"
kind: Discovery
metadata: 
  name: "airflow-discovery"

type: airflow

instance:
  - name: "airflow-1"
    includes:
      - internal
    options: 
      host: "airflow"
      port: "8280"
      username: "file:/opt/secrets/airflowusername"
      password: "file:/opt/secrets/airflowpassword"
      ssl: "false"
    classification:
      team: "dataplatform"
      domain: "jobs"
      capability: "jobs"
      #ignore, skip, replace, mergeLeft, mergeRight
    duplicatesStrategy: "ignore" 

