apiVersion: "v1"
kind: Discovery
metadata: 
  name: "pg-discovery"

type: postgres
instance:
  - name: "pg-1"
    enabled: "${env.SSL_STATE!=on}"
    includes:
      - internal
    classification:
      team: "datahoarders"
      domain: "storage"
      capability: "dataretention"
    options: 
      host: "postgres"
      port: "5432"
      username: "file:/opt/secrets/pgusername"
      password: "file:/opt/secrets/pgpassword"
      ssl: "false"
      database: "servicing"
      #ignore, skip, replace, mergeLeft, mergeRight
    duplicatesStrategy: "ignore" 

  - name: "pg-1"
    enabled: "${env.SSL_STATE==on}"  
    includes:
      - internal
    classification:
      team: "datahoarders"
      domain: "storage"
      capability: "dataretention"
    options: 
      host: "postgres"
      port: "5432"
      username: "file:/opt/secrets/pgusername"
      password: "file:/opt/secrets/pgpassword"
      ssl: "true"
      cafile: "/opt/secrets/ca.crt"
      database: "servicing"
      #ignore, skip, replace, mergeLeft, mergeRight
    duplicatesStrategy: "ignore" 


  - name: "pg-2"
    enabled: "${env.SSL_STATE!=on}"
    options: 
      host: "postgres"
      port: "5432"
      username: "file:/opt/secrets/pgusername"
      password: "file:/opt/secrets/pgpassword"
      ssl: "false"
      database: "preferences"
      #ignore, skip, replace, mergeLeft, mergeRight
    duplicatesStrategy: "ignore" 
  - name: "pg-2"
    enabled: "${env.SSL_STATE==on}"
    options: 
      host: "postgres"
      port: "5432"
      username: "file:/opt/secrets/pgusername"
      password: "file:/opt/secrets/pgpassword"
      ssl: "true"
      cafile: "/opt/secrets/ca.crt"
      database: "servicing"      
      #ignore, skip, replace, mergeLeft, mergeRight
    duplicatesStrategy: "ignore"     
