apiVersion: "v1"
kind: Resource
class: Mailbox
metadata: 
  name: "customer email"
  description: "Mailbox used by notifications to send emails to customer"
  license: "private"
dependencies:
  upstream: []
  downstream: []
  triggers: []
  providedBy: gmail
classification:
    tag: ["preferences", "email"]
    domain: "preferences"
    team: "alerters"
    capability: "correspondence"
