
options:
  log:
    level: "info"
    format: "json"
  server:
    address: ":8080"

  catalog:
    location: "http://localhost:8080/api/catalog"


  serve:
    search:
      index: ["layer", "tier", "team", "domain", "contact", "type",  "language", "name"]
      parallel: 1
    refresh:
      frequency: 5m
    source:
      - location: /opt/examples/datasets/my-account
        extension: ".yaml"
        name: "gitsync"
        enabled: true
      - location: /opt/examples/datasets/discovered-items
        extension: ".yaml"
        name: "discovery-data"
        enabled: true        


  discovery:
    source:
      - location: /opt/examples/datasets/docker-discovery
        extension: ".yaml"
        name: "discover-1"
        enabled: true
    enabledEngines:
      - k8s
      - cassandra
      - kafka
      - airflow
      - postgres
    refresh:
      frequency: 10m
    target:
      name: "sink"
      location: "/opt/examples/datasets/discovered-items"
      options: {}




