apiVersion: "v1"
kind: Discovery
metadata: 
  name: "s3-discovery"

type: aws
instance:
  - name: "s3-1"
    filter:
      resources: ["s3", "lambda", "sqs", "sns"]
      excludes: [".*"]
      includes: ["spark.*", "gpg.*", ".*biller", "aws-sts.*", "save.*", "sqs.*", "sns.*"]

    includes:
      - internal
      - data-stuff
    classification:
      team: "datahoarders"
      domain: "storage"
      capability: "dataretention"
    options: 
      username: "file:./tmp/access_key"
      password: "file:./tmp/secret_key"
      region: "ap-southeast-2"

      ssl: "true"
    #ignore, skip, replace, mergeLeft, mergeRight
    duplicatesStrategy: "skip" 
