apiVersion: "v1"
kind: Discovery
metadata: 
  name: "airflow-discovery"

type: airflow

instance:
  - name: "airflow-1"
    includes:
      - internal
    options: 
      host: "airflow.ops-catalog.io"
      port: "80"
      username: "admin"
      password: "file:./tmp/airflow"
      ssl: "false"
    classification:
      team: "dataplatform"
      domain: "jobs"
      capability: "jobs"
      #ignore, skip, replace, mergeLeft, mergeRight
    duplicatesStrategy: "ignore" 

