apiVersion: "v1"
kind: Discovery
metadata: 
  name: "cassandra-discovery"

type: cassandra

instance:
  - name: "cassandra-1"
    options: 
      host: "cassandra.ops-catalog.io"
      port: "9042"
      username: "cassandra"
      password: "file:./tmp/casspassword"
      ssl: "true"
      cafile: "./tmp/ca.crt"
    includes:
      - internal
    classification:
      team: "datahoarders"
      domain: "storage"
      capability: "dataretention"
      #ignore, skip, replace, mergeLeft, mergeRight
    duplicatesStrategy: "skip"       
