apiVersion: "v1"
kind: Discovery
metadata: 
  name: "github"

type: git

instance:
  - name: "personal-github"
    includes:
      - internal
    filter: 
      includes: [".*by-example", ".*playground"]
    options: 
      host: "api.github.com"
      port: "443"
      username: "file:./tmp/githubusername"
      password: "file:./tmp/githubpassword"
      ssl: "true"
    classification:
      team: "devexp"
      domain: "platform"
      capability: "operations"
    #ignore, skip, replace, mergeLeft, mergeRight
    duplicatesStrategy: "ignore" 

  - name: "org-github"
    includes:
      - internal
    filter:
      excludes: [".*"]
      includes: [".*examples", ".*specification"]
    options: 
      host: "api.github.com"
      port: "443"
      username: "file:./tmp/githubusername"
      password: "file:./tmp/githubpassword"
      ssl: "true"
      org: "ops-catalog"
      use-hints: "false"
    classification:
      team: "devexp"
      domain: "platform"
      capability: "operations"
    #ignore, skip, replace, mergeLeft, mergeRight
    duplicatesStrategy: "ignore" 
