apiVersion: "v1"
kind: Discovery
metadata: 
  name: "github"

type: git

instance:
  - name: "github"
    includes:
      - internal
    options: 
      host: "api.github.com"
      port: "443"
      username: "file:./tmp/githubusername"
      password: "file:./tmp/githubpassword"
      ssl: "true"
    classification:
      team: "keepers"
      domain: "storage"
      capability: "operations"
    #ignore, skip, replace, mergeLeft, mergeRight
    duplicatesStrategy: "ignore" 

