apiVersion: "v1"
kind: Discovery
metadata: 
  name: "k8s-discovery"

type: k8s
instance:
  - name: "k8s"
    filter:
      excludes: ["local-path-.*", "metrics-.*", "coredns", "envoy.*gateway.*"]
    includes:
      - internal
    options: 
      host: "k8s-read.ops-catalog.io"
      port: "80"
      ssl: "false"
    classification:
      team: "devops"
      domain: "platform"
      capability: "operations"
    #ignore, skip, replace, mergeLeft, mergeRight
    duplicatesStrategy: "ignore" 