apiVersion: "v1"
kind: Discovery
metadata: 
  name: "s3-discovery"

type: s3 
instance:
  - name: "s3-1"
    filter:
      excludes: [".*"]
      includes: ["spark.*", "gpg.*", ".*biller", "aws-sts.*"]

    includes:
      - internal
      - data-stuff
    classification:
      team: "datahoarders"
      domain: "storage"
      capability: "dataretention"
    options: 

      host: "s3.ap-southeast-2.amazonaws.com"
      port: "443"

      username: "file:./tmp/access_key"
      password: "file:./tmp/secret_key"
      region: "ap-southeast-2"

      ssl: "true"
    #ignore, skip, replace, mergeLeft, mergeRight
    duplicatesStrategy: "skip" 
